# Generated by Django 2.1.4 on 2019-06-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountdetail',
            name='kind',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='amounttotal',
            name='kind',
            field=models.CharField(max_length=4),
        ),
    ]
